services:
  bingo-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bingo-server
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/bingo
    ports:
      - "3000:3000"
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: bingo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
